services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        env_file:
            - .env
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - REDIS_HOST=redis
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        networks:
            - web

    redis:
        image: redis:latest
        container_name: redis_service
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - web

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "financial"
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - web

networks:
    web:
        driver: bridge

volumes:
    postgres_data:
    redis_data:
