"""add column withdrawals to portfolios

Revision ID: 1ded1f15a953
Revises: 6cfaad458c4c
Create Date: 2025-06-12 22:33:39.165304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ded1f15a953'
down_revision: Union[str, None] = '6cfaad458c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('withdrawals', sa.DECIMAL(precision=24, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'withdrawals')
    # ### end Alembic commands ###
