"""add holdings_history table

Revision ID: 26a5c9e32115
Revises: 34b6c15d6bd1
Create Date: 2025-06-17 17:13:52.465874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a5c9e32115'
down_revision: Union[str, None] = '34b6c15d6bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('units', sa.DECIMAL(precision=24, scale=8), nullable=False),
    sa.Column('total_deposit', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('total_withdraw', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('current_value', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('pnl', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'portfolio_id', 'date', name='uq_holding_history')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings_history')
    # ### end Alembic commands ###
