"""add_stripe_related_columns

Revision ID: 34b6c15d6bd1
Revises: ef8b2f956fae
Create Date: 2025-06-16 01:54:56.446123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b6c15d6bd1'
down_revision: Union[str, None] = 'ef8b2f956fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_onboarding_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_onboarding_completed')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'stripe_account_id')
    # ### end Alembic commands ###
