"""update portfolio related tables

Revision ID: 53ace85facca
Revises: 684db058eabc
Create Date: 2025-06-02 22:33:39.476847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ace85facca'
down_revision: Union[str, None] = '684db058eabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_gains',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gain_pct', sa.DECIMAL(precision=7, scale=3), nullable=False),
    sa.Column('profit', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('portfolio_id', 'date')
    )
    op.add_column('portfolio_snapshots', sa.Column('balance', sa.DECIMAL(precision=24, scale=2), nullable=False))
    op.create_index('ix_snap_portfolio_date', 'portfolio_snapshots', ['portfolio_id', 'snapshot_date'], unique=False)
    op.drop_index(op.f('ix_portfolios_oid_myfx'), table_name='portfolios')
    op.create_index(op.f('ix_portfolios_oid_myfx'), 'portfolios', ['oid_myfx'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_oid_myfx'), table_name='portfolios')
    op.create_index(op.f('ix_portfolios_oid_myfx'), 'portfolios', ['oid_myfx'], unique=False)
    op.drop_index('ix_snap_portfolio_date', table_name='portfolio_snapshots')
    op.drop_column('portfolio_snapshots', 'balance')
    op.drop_table('daily_gains')
    # ### end Alembic commands ###
