"""update auth tables

Revision ID: a8f06096de2d
Revises: 59272f79ed08
Create Date: 2025-06-29 18:12:19.306234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f06096de2d'
down_revision: Union[str, None] = '59272f79ed08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'verified')
    op.drop_column('identities', 'secret_hash')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', postgresql.BYTEA(), nullable=False))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.add_column('identities', sa.Column('secret_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('identities', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
