"""create table "admin_transfers"

Revision ID: f39cb26e99b4
Revises: 194d8dd11574
Create Date: 2025-06-10 18:22:28.847117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f39cb26e99b4'
down_revision: Union[str, None] = '194d8dd11574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('direction', postgresql.ENUM('DEPOSIT', 'WITHDRAW', name='transferdirection'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('method', postgresql.ENUM('STRIPE', 'BANK', name='transfermethod'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', name='paymentstatus', create_type=False), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_transfers_status'), 'admin_transfers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_transfers_status'), table_name='admin_transfers')
    op.drop_table('admin_transfers')
    # ### end Alembic commands ###
