"""add deposits column to portfolios table

Revision ID: fb257d1590aa
Revises: 53ace85facca
Create Date: 2025-06-03 17:37:05.965840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb257d1590aa'
down_revision: Union[str, None] = '53ace85facca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('deposits', sa.DECIMAL(precision=24, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'deposits')
    # ### end Alembic commands ###
