"""Add units column to invest_orders

Revision ID: fbb5307d28a7
Revises: 1ded1f15a953
Create Date: 2025-06-13 16:30:48.575810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb5307d28a7'
down_revision: Union[str, None] = '1ded1f15a953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invest_orders', sa.Column('units', sa.DECIMAL(precision=24, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invest_orders', 'units')
    # ### end Alembic commands ###
