"""add table invest_orders

Revision ID: ffbbeaf58c89
Revises: b3b47eb583e6
Create Date: 2025-06-05 17:49:17.510461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbbeaf58c89'
down_revision: Union[str, None] = 'b3b47eb583e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invest_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('INVEST', 'WITHDRAW', name='orderdirection'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXECUTED', 'FAILED', name='investorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('holdings_portfolio_id_fkey'), 'holdings', type_='foreignkey')
    op.create_foreign_key(None, 'holdings', 'portfolios', ['portfolio_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.create_foreign_key(op.f('holdings_portfolio_id_fkey'), 'holdings', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_table('invest_orders')
    # ### end Alembic commands ###
